version: '3'
services:
  chat-gpt:
    build: .
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/chat_gpt_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_PASSWORD: ${ENV_REDIS_PASSWORD}
      SPRING_PROFILES_ACTIVE: test
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - redis
    networks:
      - chat-gpt-network

  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_PASSWORD}
      MYSQL_DATABASE: chat_gpt_db
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - chat-gpt-network

  redis:
    image: redis:5.0.14
    command: redis-server --requirepass ${ENV_REDIS_PASSWORD}
    ports:
      - 16379:6379
    volumes:
      - redis-data:/data
    networks:
      - chat-gpt-network

volumes:
  mysql-data:
  redis-data:

networks:
  chat-gpt-network:
    driver: bridge
