version: '3'
services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: 23122918Lxc
      MYSQL_DATABASE: chat_gpt_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - chat-gpt-network

  redis:
    image: redis:5.0.14
    command: redis-server --requirepass 23122918lxc
    volumes:
      - redis-data:/data
    networks:
      - chat-gpt-network

  chat-gpt:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - redis
    networks:
      - chat-gpt-network

volumes:
  mysql-data:
  redis-data:

networks:
  chat-gpt-network:
    driver: bridge
